export const FRANCY = {
  name: 'Francy Molano Nails Studio',
  shortName: 'Francy Molano',
  whatsapp: '573106920842',
  phoneDisplay: '310 692 0842',
  phoneE164: '+573106920842',
  instagram: 'francymolano_paipa',
  tiktok: 'francymolano_nails',
  address: 'Edificio Valenci al Medio, Cra. 22 #26-63, Paipa',
  street: 'Cra. 22 #26-63',
  city: 'Paipa',
  region: 'Boyacá',
  postalCode: '150410',
  country: 'CO',
  geo: { lat: 5.7812, lng: -73.1178 },
  plusCode: 'QVJM+JJ Paipa, Boyacá',
  googleRating: 4.5,
  googleReviews: 11,
  mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Francy+Molano+Nails+Studio+Paipa+Boyaca',
  priceRange: '$$',
  currency: 'COP',
  closing: '18:00',
  url: 'https://francy-molano.vercel.app',
  seoTitle: 'Uñas Semipermanentes en Paipa | Francy Molano',
  seoDescription:
    'Estudio de uñas en Paipa, Boyacá. Manicure, semipermanente, acrílicas, pedicure spa, cejas y pestañas con producto profesional. Agenda tu cita por WhatsApp.',
  hours: [
    {
      label: 'Lunes a viernes',
      value: '9:00 am – 12:30 pm · 2:00 pm – 6:00 pm',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    {
      label: 'Sábado',
      value: '9:00 am – 12:30 pm · 2:00 pm – 6:00 pm',
      days: ['Saturday'],
      opens: '09:00',
      closes: '18:00',
    },
    {
      label: 'Domingo y festivos',
      value: 'Solo con cita previa',
      days: [],
      opens: '',
      closes: '',
    },
  ],
} as const;
